[dependencies]
required = []
optional = {}

[packages]
required = ['.']
optional = {}

[subrepos]
required = {} # {remote: [head, [options], [flags]]}
optional = {} # {option: {remote: [head, [options], [flags]]}}
